name = "aquifer-mcp"
main = "src/index.ts"
compatibility_date = "2025-03-14"
compatibility_flags = ["nodejs_compat"]

[vars]
AQUIFER_ORG = "BibleAquifer"
DOCS_REPO = "docs"

[[kv_namespaces]]
binding = "AQUIFER_CACHE"
id = "aa19ca4a80aa48a5bf25317fd9b2d4e1"
preview_id = "f73869e2e7ac4e04a9ee2fa3887ceefe"
