import {it,expect,vi,afterEach} from 'vitest';
import {sourceCatalog} from './catalog-server.js';
import type {AquiferStorage} from './storage.js';
import type {Env} from './types.js';
const revision='a'.repeat(40),identity={organization:'BibleAquifer',resourceCode:'FIAKeyTerms',language:'eng',revision};
function storage(){const data=new Map();return {getJSON:async(key:string)=>({data:data.get(key)??null}),putJSON:async(key:string,value:unknown)=>{data.set(key,structuredClone(value));return true;}} as unknown as AquiferStorage;}
afterEach(()=>vi.unstubAllGlobals());
it('binds original pinned JSON bytes and discovers embedded dictionary audio without fetching assets',async()=>{
 const raw=' \n'+JSON.stringify([{content_id:'eng-t1-v1-audio',language:'eng',title:'Abraham',media_type:'Text',content:'<a href="https://example.org/abraham.mp3">Audio</a>'}])+'\n';
 const calls:string[]=[];vi.stubGlobal('fetch',async(url:string)=>{calls.push(url);return new Response(url.includes('/git/trees/')?JSON.stringify({sha:'b'.repeat(40),truncated:false,tree:[{type:'blob',path:'eng/json/000001.content.json'}]}):raw)});
 const result=await sourceCatalog(identity,{} as Env,storage());expect(result.complete).toBe(true);expect(result.entries[0]?.media[0]?.kind).toBe('audio');expect(result.entries[0]?.contentFileSha256).toBe(Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(raw))),x=>x.toString(16).padStart(2,'0')).join(''));expect(calls).toHaveLength(3);expect(calls[1]).toContain(`/${revision}/eng/json/`);
});
it('continues only from server-owned state and keeps actual localized IDs',async()=>{
 const store=storage();vi.stubGlobal('fetch',async(url:string)=>new Response(url.includes('/git/trees/')?JSON.stringify({sha:'b'.repeat(40),truncated:false,tree:Array.from({length:5},(_,i)=>({type:'blob',path:`spa/json/${i}.content.json`}))}):JSON.stringify([{content_id:url.split('/').at(-1),language:'spa',content:'texto'}])));
 const first=await sourceCatalog({...identity,language:'spa'},{} as Env,store);expect(first.complete).toBe(false);expect(first.entries).toHaveLength(4);const final=await sourceCatalog({...identity,language:'spa'},{} as Env,store,first.nextCursor!);expect(final.complete).toBe(true);expect(final.entries).toHaveLength(5);expect(final.entries.every(e=>!e.contentId.startsWith('eng-'))).toBe(true);await expect(sourceCatalog({...identity,language:'spa'},{} as Env,storage(),first.nextCursor!)).rejects.toThrow('snapshot unavailable');
});
it('reports failed and truncated discovery without false absence',async()=>{vi.stubGlobal('fetch',async()=>new Response(JSON.stringify({sha:'b'.repeat(40),truncated:true,tree:[]})));const result=await sourceCatalog(identity,{} as Env,storage());expect(result.complete).toBe(false);expect(result.expectedFiles).toBeNull();});
it('binds known collection rights from pinned matching-language metadata only',async()=>{vi.stubGlobal('fetch',async(url:string)=>new Response(JSON.stringify(url.includes('/git/trees/')?{sha:'b'.repeat(40),truncated:false,tree:[{type:'blob',path:'eng/json/1.content.json'}]}:url.endsWith('metadata.json')?{resource_metadata:{language:'eng',license_info:{title:'CC BY-SA 4.0'}}}:[{content_id:'one',content:'<audio src="https://example.org/a.mp3"></audio>'}])));const result=await sourceCatalog(identity,{} as Env,storage());expect(result.entries[0]?.media[0]?.rights).toEqual({scope:'collection',statement:'{"title":"CC BY-SA 4.0"}',metadataUrl:`https://raw.githubusercontent.com/BibleAquifer/FIAKeyTerms/${revision}/eng/metadata.json`});expect(result.entries[0]?.media[0]?.assetRights).toBe('unverified');});
it('stops oversized tree bodies before parsing or fetching content',async()=>{const fetch=vi.fn(async()=>new Response(' '.repeat(8_000_001)));vi.stubGlobal('fetch',fetch);await expect(sourceCatalog(identity,{} as Env,storage())).rejects.toThrow('byte budget');expect(fetch).toHaveBeenCalledTimes(1);});
it('rejects invalid language before constructing any network request',async()=>{const fetch=vi.fn();vi.stubGlobal('fetch',fetch);await expect(sourceCatalog({...identity,language:'../spa'},{} as Env,storage())).rejects.toThrow();expect(fetch).not.toHaveBeenCalled();});
