import{describe,it,expect,vi}from'vitest';import{buildLanguageCatalog,languageCatalogPage,pinnedCatalogUrl,pinnedCatalogCacheKey,type CatalogIdentity,type Discovery,type ContentReader}from'./language-catalog.js';
const id:CatalogIdentity={organization:'BibleAquifer',resourceCode:'FIAKeyTerms',language:'spa',revision:'a'.repeat(40)};
const path=(n:number)=>`spa/json/${String(n).padStart(6,'0')}.content.json`;
const discovery=(paths=[path(1)]):Discovery=>({revision:id.revision,language:'spa',method:'git-tree',paths,exhaustive:true});
const article=(content_id='spa-t1',language:string|undefined='spa',content='<p>Abraham</p>')=>({content_id,language,content,title:'Abraham',media_type:'Text',associations:{passage:[]}});
const reader=(files:Record<string,unknown>):ContentReader=>async request=>request.path in files?{status:'found',path:request.path,revision:request.revision,content:JSON.stringify(files[request.path])}:{status:'missing'};
describe('language catalog source and continuation',()=>{
 it('includes only actual requested-language rows and distinguishes file/HTML hashes',async()=>{const e=await buildLanguageCatalog({identity:id,discovery:discovery(),read:reader({[path(1)]:[article()]})});expect(e.complete).toBe(true);expect(e.entries.map(e=>e.contentId)).toEqual(['spa-t1']);expect(e.entries[0]!.contentFileSha256).not.toBe(e.entries[0]!.articleHtmlSha256);expect(e.entries[0]!.aliases).toEqual([]);expect(e.entries.some(e=>e.contentId==='eng-t1-v1-audio')).toBe(false);});
 it('records missing language from verified path without ignoring a conflicting declaration',async()=>{const e=await buildLanguageCatalog({identity:id,discovery:discovery(),read:reader({[path(1)]:[{...article('local'),language:undefined},article('wrong','eng')]})});expect(e.entries).toHaveLength(1);expect(e.entries[0]!.languageBasis).toBe('source-path');expect(e.complete).toBe(false);expect(e.failedFiles[0]!.code).toBe('article-language-mismatch');});
 it('continues deterministically with bounded files and a Unicode query, separate result paging',async()=>{const d=discovery([path(3),path(1),path(2),path(1)]),read=reader({[path(1)]:[article('1')],[path(2)]:[article('2')],[path(3)]:[article('3')]});let e=await buildLanguageCatalog({identity:id,discovery:d,read,maxFiles:1,queryKey:'audio español'});expect(e.entries.map(e=>e.contentId)).toEqual(['1']);expect(e.complete).toBe(false);expect(e.pendingFiles).toEqual([path(2),path(3)]);e=await buildLanguageCatalog({identity:id,discovery:d,read,maxFiles:2,queryKey:'audio español',previous:e,cursor:e.nextCursor!});expect(e.entries.map(e=>e.contentId)).toEqual(['1','2','3']);expect(e.complete).toBe(true);expect(languageCatalogPage(e,1,1)).toMatchObject({offset:1,knownEntries:3,totalIsExact:true,nextOffset:2});});
 it('rejects changed query, revision, discovery and old schema cursors',async()=>{const d=discovery([path(1),path(2)]),read=reader({[path(1)]:[]});const e=await buildLanguageCatalog({identity:id,discovery:d,read,maxFiles:1});for(const patch of[{queryKey:'video'},{identity:{...id,revision:'b'.repeat(40)},discovery:{...d,revision:'b'.repeat(40)}},{discovery:discovery([path(1),path(3)])},{previous:{...e,schemaVersion:1}}])await expect(buildLanguageCatalog({identity:id,discovery:d,read,previous:e,cursor:e.nextCursor!,...patch} as Parameters<typeof buildLanguageCatalog>[0])).rejects.toThrow();});
 it('distinguishes valid empty, incomplete discovery and missing/error content',async()=>{const empty=await buildLanguageCatalog({identity:id,discovery:discovery(),read:reader({[path(1)]:[]})});expect(languageCatalogPage(empty).verifiedEmpty).toBe(true);for(const d of[{...discovery(),exhaustive:false},{...discovery(),truncated:true}]){const e=await buildLanguageCatalog({identity:id,discovery:d,read:reader({[path(1)]:[]})});expect(e.complete).toBe(false);expect(languageCatalogPage(e).verifiedEmpty).toBe(false);}const missing=await buildLanguageCatalog({identity:id,discovery:discovery(),read:reader({})});expect(missing.scanComplete).toBe(false);expect(missing.failedFiles[0]!.code).toBe('missing-file');});
 it('quarantines conflicting duplicate IDs across continuation and deduplicates exact copies',async()=>{const d=discovery([path(1),path(2),path(3)]),read=reader({[path(1)]:[article('same')],[path(2)]:[article('same')],[path(3)]:[article('same','spa','different')]});let e=await buildLanguageCatalog({identity:id,discovery:d,read,maxFiles:2});expect(e.entries).toHaveLength(1);e=await buildLanguageCatalog({identity:id,discovery:d,read,previous:e,cursor:e.nextCursor!});expect(e.entries).toEqual([]);expect(e.conflicts).toEqual(['same']);expect(e.complete).toBe(false);});
 it('binds only explicit aliases targeting verified localized entries',async()=>{const metadata={path:'eng/metadata.json',language:'eng',revision:id.revision,content:JSON.stringify({article_metadata:{'eng-t1':{localizations:{spa:{content_id:'spa-t1'}}},'eng-missing':{localizations:{spa:{content_id:'absent'}}}}})};const e=await buildLanguageCatalog({identity:id,discovery:discovery(),read:reader({[path(1)]:[article()]}),localizationMetadata:metadata});expect(e.entries[0]!.aliases).toHaveLength(1);expect(e.entries[0]!.aliases[0]).toMatchObject({id:'eng-t1',metadataPath:'eng/metadata.json',revision:id.revision});});
 it('requires exact reader path/revision and bounds oversized responses',async()=>{for(const read of[(async()=>({status:'found',path:path(1),revision:'main',content:'[]'})),(async()=>({status:'found',path:path(2),revision:id.revision,content:'[]'})),(async()=>({status:'found',path:path(1),revision:id.revision,content:' '.repeat(20)}))] as ContentReader[]){const e=await buildLanguageCatalog({identity:id,discovery:discovery(),read,maxBytes:10});expect(e.complete).toBe(false);expect(e.failedFiles).toHaveLength(1);}});
 it('does not claim guessed discovery exhaustive and rejects traversal',async()=>{for(const d of[{...discovery(),method:'probe' as const},{...discovery(),paths:['spa/json/../eng/file.content.json']}])await expect(buildLanguageCatalog({identity:id,discovery:d,read:reader({})})).rejects.toThrow();});
 it('has versioned pinned URL and cache identities, never main',()=>{expect(pinnedCatalogUrl(id,path(1))).toContain('/'+'a'.repeat(40)+'/spa/json/');expect(pinnedCatalogCacheKey('content',id,path(1))).toContain('pinned-content:v2:');expect(pinnedCatalogCacheKey('content',id,path(1))).not.toBe(pinnedCatalogCacheKey('content',{...id,revision:'b'.repeat(40)},path(1)));expect(()=>pinnedCatalogUrl(id,'eng/metadata.json')).toThrow();});
 it('preserves source HTML and primary English behavior without global fetch',async()=>{const fetch=vi.spyOn(globalThis,'fetch'),eng={...id,language:'eng'},p='eng/json/000001.content.json',html='<audio src="a.mp3"></audio>';const e=await buildLanguageCatalog({identity:eng,discovery:{...discovery(),language:'eng',paths:[p]},read:reader({[p]:[article('eng-t1','eng',html)]})});expect(e.entries[0]!.content).toBe(html);expect(e.entries[0]!.language).toBe('eng');expect(fetch).not.toHaveBeenCalled();fetch.mockRestore();});
 it('hashes original UTF-8 bytes, including JSON whitespace, before parsing',async()=>{const plain=JSON.stringify([article()]),spaced='  '+plain+'\n';const read:ContentReader=async r=>({status:'found',path:r.path,revision:r.revision,content:new TextEncoder().encode(spaced)});const e=await buildLanguageCatalog({identity:id,discovery:discovery(),read});const expected=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(spaced))),b=>b.toString(16).padStart(2,'0')).join('');expect(e.entries[0]!.contentFileSha256).toBe(expected);});
 it('reports invalid JSON and thrown reads without a verified empty claim',async()=>{for(const read of[(async()=>{throw Error('network');}),(async r=>({status:'found',path:r.path,revision:r.revision,content:'broken'}))] as ContentReader[]){const e=await buildLanguageCatalog({identity:id,discovery:discovery(),read});expect(e.complete).toBe(false);expect(languageCatalogPage(e).verifiedEmpty).toBe(false);}});
 it('rejects metadata from another revision before granting aliases',async()=>{await expect(buildLanguageCatalog({identity:id,discovery:discovery(),read:reader({[path(1)]:[article()]}),localizationMetadata:{path:'eng/metadata.json',language:'eng',revision:'b'.repeat(40),content:'{}'}})).rejects.toThrow('metadata identity');});
 it('serializes reader calls and reports bounded progress separately',async()=>{let active=0,maxActive=0;const read:ContentReader=async r=>{active++;maxActive=Math.max(maxActive,active);await Promise.resolve();active--;return{status:'found',path:r.path,revision:r.revision,content:'[]'};};const e=await buildLanguageCatalog({identity:id,discovery:discovery([path(1),path(2),path(3)]),read,maxFiles:2});expect(maxActive).toBe(1);expect(e.scannedFiles).toBe(2);expect(e.pendingFiles).toEqual([path(3)]);expect(e.expectedFiles).toBe(3);expect(e.complete).toBe(false);});

 it('does not let an alias shadow an exact content ID',async()=>{const metadata={path:'eng/metadata.json',language:'eng',revision:id.revision,content:JSON.stringify({article_metadata:{actual:{localizations:{spa:{content_id:'other'}}}}})};const e=await buildLanguageCatalog({identity:id,discovery:discovery(),read:reader({[path(1)]:[article('actual'),article('other')]}),localizationMetadata:metadata});expect(e.entries.every(e=>e.aliases.length===0)).toBe(true);expect(e.entries.map(e=>e.contentId)).toEqual(['actual','other']);});
 it('keeps failed-only scans explicit and restartable, never verified empty',async()=>{const d=discovery(),failed=await buildLanguageCatalog({identity:id,discovery:d,read:reader({})});expect(failed.nextCursor).toBeNull();expect(failed.complete).toBe(false);const restarted=await buildLanguageCatalog({identity:id,discovery:d,read:reader({[path(1)]:[]})});expect(restarted.complete).toBe(true);expect(failed.complete).toBe(false);});

});
